sudo: required

language: ruby

rvm:
  - 2.2.0

services:
  - docker

before_install:
  - docker build -t commutator/dynamo-local -f Dockerfile.ci .
  - docker run -d -p 127.0.0.1:8000:8000 commutator/dynamo-local -inMemory -port 8000
  - docker ps

script:
  - bundle exec rspec
